### ISSUE TITLE
Basic command line calculator

### ISSUE THREAD

**Issue by PTRett** [aggie-coding-club/Engineer_Calculator#2]
Basic calculator used from command line supporting basic arithmetic functions (+ - / *)

**Comment by mfreano24** [comment]
[Calculator.zip](https://github.com/aggie-coding-club/Engineer_Calculator/files/2496993/Calculator.zip)
I put more than just the four basic functions in there, and included other functions (I think 32 if you count each individual trig function. If it's too much, feel free to scale it back or make something simpler.)
//Operations:
Addition (+)
Subtraction (-)
Multiplication (*)
Division (/)
nth Root (nrt)
*10^n (e)
nth power (^)
Log custom base (logn)
//DO NOT PROMPT FOR SECOND NUMBER
Square Root (sqrt)
Squared (^2)
Cubed (^3)
Natural log (ln)
Log Base 10 (log10)
Trig Functions (sin) (cos) (tan) (you get the idea)
Inverse Trig Functions (asin) (acos) (atan) (you get the idea again)
Trig Functions in degrees (sind) (cosd) (tand) (etc)
